### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by xandros6** [sunshine-tech/esp_provisioning#9]
Hi,
to upgrade this dependencies:

  protobuf: ^1.1.1
  cryptography: ^1.4.1

To

  protobuf: ^2.0.0
  cryptography: ^2.0.1

A refactoring of Security1 is needed due to new API of "cryptography" library.
Can you help me in the migration please?

Thanks.
Sandro

**Comment by bretmh** [comment]
Just use flutter dependency overrides.
